service: my-serverless-project

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"

functions:
  user:
    handler: lambdas/user/user.handler
    events:
      - httpApi:
          path: /user/{proxy+}
          method: ANY

  cart:
    handler: lambdas/cart/cart.handler
    events:
      - httpApi:
          path: /cart/{proxy+}
          method: ANY
